"""empty message

Revision ID: 7861e1b1bbb1
Revises: c395a7c9a8ad
Create Date: 2022-11-13 22:39:10.422078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7861e1b1bbb1'
down_revision = 'c395a7c9a8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column('User', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'image')
    op.drop_column('Post', 'image')
    # ### end Alembic commands ###
